version: '3.4'

services:
  api:
    container_name: crawler-api
    image: crawlerapi
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    expose:
      - 8686:8686

  nginx:
    container_name: crawler-api-nginx
    image: nginx:latest
    ports:
      - 8686:8686
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

