version: '3.4'

services:
  api:
    container_name: crawler-api
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8686 --reload"
    image: crawlerapi
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
    env_file:
      - .env
    expose:
      - 8686:8686

  nginx:
    container_name: crawler-api-nginx
    image: nginx:latest
    ports:
      - 8686:8686
    volumes:
      - ./app:/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

