# fly.toml app configuration file generated for jusbrasil-crawler on 2023-08-01T22:08:54-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jusbrasil-crawler"
primary_region = "gig"

[build]

[http_service]
  internal_port = 8686
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
